export const INDUSTRY_ROLES: Record<string, string[]> = {
  Finance: [
    "Financial Analyst",
    "Investment Banker",
    "Accountant",
    "Certified Public Accountant (CPA)",
    "Auditor",
    "Financial Controller",
    "CFO (Chief Financial Officer)",
    "Wealth Advisor",
    "Actuary",
    "Risk Manager",
    "Compliance Officer",
    "Portfolio Manager",
    "Quantitative Analyst (Quant)",
    "Tax Consultant",
    "Credit Analyst",
    "Private Equity Analyst",
    "Venture Capitalist",
    "Treasury Analyst",
    "Fraud Investigator",
    "Economist",
    "Underwriter",
    "Claims Adjuster",
    "Hedge Fund Manager",
    "Financial Planner",
    "Equity Research Analyst",
  ],
  Technology: [
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile Developer (iOS)",
    "Mobile Developer (Android)",
    "Game Developer",
    "Unity Developer",
    "Data Scientist",
    "Data Analyst",
    "Data Engineer",
    "Machine Learning Engineer",
    "AI Engineer",
    "NLP Engineer",
    "Computer Vision Engineer",
    "DevOps Engineer",
    "Site Reliability Engineer (SRE)",
    "Cloud Architect (AWS/GCP/Azure)",
    "Solutions Architect",
    "Systems Architect",
    "Product Manager",
    "Technical Product Manager",
    "Product Owner",
    "Scrum Master",
    "Agile Coach",
    "Engineering Manager",
    "Director of Engineering",
    "CTO (Chief Technology Officer)",
    "CIO (Chief Information Officer)",
    "QA Engineer",
    "SDET (Software Development Engineer in Test)",
    "Test Automation Engineer",
    "Cybersecurity Analyst",
    "Security Engineer",
    "Penetration Tester",
    "Information Security Officer",
    "Systems Administrator",
    "Database Administrator (DBA)",
    "Network Engineer",
    "IT Support Specialist",
    "AR/VR Developer",
    "Blockchain Developer",
    "Smart Contract Engineer",
    "Web3 Developer",
    "Developer Advocate",
    "Developer Relations (DevRel)",
    "Technical Writer",
    "ERP Consultant",
  ],
  Business: [
    "Business Analyst",
    "Business Development Manager",
    "Entrepreneur / Founder",
    "Product Manager",
    "Operations Manager",
    "Strategy Associate",
    "General Manager",
    "Chief Executive Officer (CEO)",
  ],
  Consulting: [
    "Management Consultant",
    "Strategy Consultant",
    "Operations Consultant",
    "HR Consultant",
    "IT Consultant",
    "Financial Consultant",
    "Healthcare Consultant",
    "Environmental Consultant",
    "Change Management Consultant",
    "Partner / Principal",
    "Business Analyst",
    "Innovation Consultant",
  ],
};

export const INDUSTRIES = Object.keys(INDUSTRY_ROLES);
