import { ExploreMentor } from "./types";

function getNextAvailability(daysAhead: number, time: string) {
  const date = new Date();
  date.setDate(date.getDate() + daysAhead);
  return {
    relative: daysAhead === 1 ? "tomorrow" : `in ${daysAhead} days`,
    formattedDate: `${date.toLocaleDateString("en-US", { weekday: "short", day: "numeric", month: "long" })} ${time}`,
  };
}

export const mockExploreMentors: ExploreMentor[] = [
  {
    id: "1",
    name: "Abdulrahman Hassan",
    role: "Senior Designer",
    company: "Andela",
    location: "London",
    sessionCount: 40,
    rating: 4.5,
    reviewCount: 20,
    bio: "You chose to improve people's well-being. You stepped out of your comfort zone...",
    category: "Tech",
    tags: ["Product Strategy", "Fintech", "Healthtech"],
    avatarUrl: "/mentors/mentor-1.png",
    isFeatured: true,
    nextAvailability: getNextAvailability(3, "11:30 AM"),
    price: "Free",
  },
  {
    id: "2",
    name: "Amina Yusuf",
    role: "VP of Product",
    company: "Paystack",
    location: "Lagos",
    sessionCount: 52,
    rating: 4.9,
    reviewCount: 38,
    bio: "Scaling fintech products across emerging markets. Let's talk user retention and go-to-market.",
    category: "Tech",
    tags: ["Product Strategy", "Fintech", "Payments"],
    avatarUrl: "/mentors/mentor-2.png",
    isFeatured: true,
    nextAvailability: getNextAvailability(2, "02:00 PM"),
    price: "N25,000",
  },
  {
    id: "3",
    name: "Chidinma Okafor",
    role: "Engineering Director",
    company: "Moniepoint",
    location: "London",
    sessionCount: 35,
    rating: 4.8,
    reviewCount: 29,
    bio: "Helping engineers transition into high-impact leadership roles and navigate distributed systems.",
    category: "Tech",
    tags: ["Engineering Leadership", "Cloud Architecture", "Career Growth"],
    avatarUrl: "/mentors/mentor-3.png",
    isFeatured: true,
    nextAvailability: getNextAvailability(1, "04:30 PM"),
    price: "Free",
  },
  {
    id: "4",
    name: "Tunde Balogun",
    role: "Head of Growth",
    company: "Flutterwave",
    location: "San Francisco",
    sessionCount: 44,
    rating: 4.7,
    reviewCount: 31,
    bio: "Specializing in customer acquisition funnels, retention mechanics, and international expansion.",
    category: "Business",
    tags: ["Growth Marketing", "B2B Sales", "Fintech"],
    avatarUrl: "/mentors/mentor-4.png",
    isFeatured: true,
    nextAvailability: getNextAvailability(4, "10:00 AM"),
    price: "N30,000",
  },
  {
    id: "5",
    name: "Zainab Adeleke",
    role: "Senior Product Designer",
    company: "Spotify",
    location: "Berlin",
    sessionCount: 60,
    rating: 5.0,
    reviewCount: 45,
    bio: "Passionate about inclusive design systems, user research methodologies, and career mentorship.",
    category: "Tech",
    tags: ["Design Systems", "UX Research", "Figma"],
    avatarUrl: "/mentors/mentor-2.png",
    isFeatured: false,
    nextAvailability: getNextAvailability(3, "01:00 PM"),
    price: "Free",
  },
  {
    id: "6",
    name: "Femi Adebayo",
    role: "Financial Analyst & Advisor",
    company: "PwC",
    location: "London",
    sessionCount: 28,
    rating: 4.6,
    reviewCount: 19,
    bio: "Advising high-growth startups on capital allocation, financial models, and seed funding rounds.",
    category: "Finance",
    tags: ["Financial Modeling", "Venture Capital", "Corporate Finance"],
    avatarUrl: "/mentors/mentor-1.png",
    isFeatured: false,
    nextAvailability: getNextAvailability(5, "11:00 AM"),
    price: "N20,000",
  },
  {
    id: "7",
    name: "Folake Williams",
    role: "Management Consultant",
    company: "McKinsey & Co",
    location: "New York",
    sessionCount: 47,
    rating: 4.9,
    reviewCount: 34,
    bio: "Strategy formulation, digital transformation, and business model innovation for enterprise leaders.",
    category: "Consulting",
    tags: ["Strategy", "Management", "Operations"],
    avatarUrl: "/mentors/mentor-3.png",
    isFeatured: false,
    nextAvailability: getNextAvailability(2, "03:30 PM"),
    price: "N35,000",
  },
  {
    id: "8",
    name: "David Adeleke",
    role: "Product Lead",
    company: "Google",
    location: "London",
    sessionCount: 55,
    rating: 4.8,
    reviewCount: 42,
    bio: "Mentoring ambitious PMs on roadmap execution, cross-functional stakeholder buy-in, and metrics.",
    category: "Tech",
    tags: ["Product Management", "AI/ML", "Strategy"],
    avatarUrl: "/mentors/mentor-4.png",
    isFeatured: false,
    nextAvailability: getNextAvailability(3, "05:00 PM"),
    price: "Free",
  },
  {
    id: "9",
    name: "Kemi Johnson",
    role: "Investment Associate",
    company: "Goldman Sachs",
    location: "London",
    sessionCount: 32,
    rating: 4.7,
    reviewCount: 22,
    bio: "Guiding young finance professionals on investment banking interviews, modeling, and private equity.",
    category: "Finance",
    tags: ["Investment Banking", "Valuation", "Career Coaching"],
    avatarUrl: "/mentors/mentor-2.png",
    isFeatured: false,
    nextAvailability: getNextAvailability(4, "02:00 PM"),
    price: "Free",
  },
  {
    id: "10",
    name: "Ibrahim Sadiq",
    role: "Strategy & Operations Lead",
    company: "Uber",
    location: "Dubai",
    sessionCount: 38,
    rating: 4.8,
    reviewCount: 26,
    bio: "Unlocking efficiency in complex operational networks and international marketplaces.",
    category: "Business",
    tags: ["Operations", "Marketplaces", "Growth Strategy"],
    avatarUrl: "/mentors/mentor-1.png",
    isFeatured: false,
    nextAvailability: getNextAvailability(3, "10:00 AM"),
    price: "N20,000",
  },
  {
    id: "11",
    name: "Ngozi Eze",
    role: "Principal Consultant",
    company: "Bain & Company",
    location: "Lagos",
    sessionCount: 41,
    rating: 4.9,
    reviewCount: 30,
    bio: "Hands-on guidance on case interview prep, structured problem solving, and consulting careers.",
    category: "Consulting",
    tags: ["Case Prep", "Management Consulting", "Leadership"],
    avatarUrl: "/mentors/mentor-3.png",
    isFeatured: false,
    nextAvailability: getNextAvailability(6, "01:30 PM"),
    price: "N25,000",
  },
  {
    id: "12",
    name: "Oluwaseun Alabi",
    role: "Senior Cloud Architect",
    company: "Microsoft",
    location: "Dublin",
    sessionCount: 29,
    rating: 4.6,
    reviewCount: 18,
    bio: "Helping software engineers master system design, Azure architecture, and cloud migrations.",
    category: "Tech",
    tags: ["System Design", "Cloud Infrastructure", "DevOps"],
    avatarUrl: "/mentors/mentor-4.png",
    isFeatured: false,
    nextAvailability: getNextAvailability(2, "11:00 AM"),
    price: "Free",
  },
];
