import { Booking } from "./types";

export const initialBookings: Booking[] = [
  // UPCOMING
  {
    id: "booking-upcoming-1",
    title: "Career Positioning",
    mentorName: "AbdulLah Mumuni",
    mentorRole: "VP Product @ Kuda",
    mentorAvatar: "/sessions/mentor-abdullah.png",
    linkedinUrl: "https://linkedin.com/in/abdullah-mumuni",
    timeFormatted: "3:00pm",
    relativeDate: "In 2 hours",
    fullDateTime: "Today · June 8th, 2026 · 03:00 pm - 03:30 pm",
    duration: "15mins",
    durationMinutes: 15,
    price: "₦25,000",
    status: "confirmed",
    statusLabel: "Confirmed",
    tab: "upcoming",
    isReadyToJoin: true,
    note: "I've been job hunting for Senior PM roles and would like to review my positioning and resume narrative.",
    goals: ["Career switch", "Fintech leadership", "Portfolio review"],
  },
  {
    id: "booking-upcoming-2",
    title: "CV Review",
    mentorName: "Hannah Oladejo",
    mentorRole: "VP Product @ Kuda",
    mentorAvatar: "/sessions/mentor-hannah.jpg",
    linkedinUrl: "https://linkedin.com/in/hannah-oladejo",
    timeFormatted: "4:20pm",
    relativeDate: "Tue, Sept 1st",
    fullDateTime: "Tuesday, Sept 1st, 2026 · 04:20 pm - 04:35 pm",
    duration: "15mins",
    durationMinutes: 15,
    price: "₦5,000",
    status: "unconfirmed",
    tab: "upcoming",
    isReadyToJoin: false,
    note: "Looking for direct feedback on 2 specific case study summaries on my CV.",
    goals: ["Resume critique", "Product strategy"],
  },
  {
    id: "booking-upcoming-3",
    title: "Career Positioning",
    mentorName: "Hannah Oladejo",
    mentorRole: "VP Product @ Kuda",
    mentorAvatar: "/sessions/mentor-hannah.jpg",
    linkedinUrl: "https://linkedin.com/in/hannah-oladejo",
    timeFormatted: "10:20am",
    relativeDate: "Wed, Sept 9th",
    fullDateTime: "Wednesday, Sept 9th, 2026 · 10:20 am - 11:20 am",
    duration: "60mins",
    durationMinutes: 60,
    price: "₦20,000",
    status: "unconfirmed",
    tab: "upcoming",
    isReadyToJoin: false,
    note: "In-depth career roadmap planning for transitioning from mid-level to principal/staff level.",
    goals: ["Career roadmap", "Salary negotiation"],
  },

  // PENDING
  {
    id: "booking-pending-1",
    title: "CV Review",
    mentorName: "AbdulLah Mumuni",
    mentorRole: "VP Product @ Kuda",
    mentorAvatar: "/sessions/mentor-abdullah.png",
    linkedinUrl: "https://linkedin.com/in/abdullah-mumuni",
    timeFormatted: "4:20pm",
    relativeDate: "Tue, Sept 1st",
    fullDateTime: "Today · June 8, 2026 · 3:00 pm - 3:30 pm",
    duration: "30 mins",
    durationMinutes: 30,
    price: "Free",
    status: "awaiting_confirmation",
    statusLabel: "Awaiting mentor confirmation",
    tab: "pending",
    note: "I've been job hunting for a while and I've not gotten positive results. I'd like to know the things I'm doing wrong.",
    goals: ["Career switch", "Fintech", "Healthtech"],
  },
  {
    id: "booking-pending-2",
    title: "Resume Review",
    mentorName: "Hannah Oladejo",
    mentorRole: "VP Product @ Kuda",
    mentorAvatar: "/sessions/mentor-hannah.jpg",
    linkedinUrl: "https://linkedin.com/in/hannah-oladejo",
    timeFormatted: "6:00pm",
    relativeDate: "Wed, Sept 2nd",
    fullDateTime: "Wednesday, Sept 2nd, 2026 · 06:00 pm - 06:45 pm",
    duration: "45 mins",
    durationMinutes: 45,
    price: "₦25,000",
    status: "awaiting_confirmation",
    statusLabel: "Awaiting mentor confirmation",
    tab: "pending",
    note: "Line by line audit of my executive summary and bullet points.",
    goals: ["Resume audit"],
  },
  {
    id: "booking-pending-3",
    title: "Interview Prep",
    mentorName: "Hannah Oladejo",
    mentorRole: "VP Product @ Kuda",
    mentorAvatar: "/sessions/mentor-hannah.jpg",
    linkedinUrl: "https://linkedin.com/in/hannah-oladejo",
    timeFormatted: "5:30pm",
    relativeDate: "Thu, Sept 3rd",
    fullDateTime: "Thursday, Sept 3rd, 2026 · 05:30 pm - 06:30 pm",
    duration: "60 mins",
    durationMinutes: 60,
    price: "₦25,000",
    status: "awaiting_confirmation",
    statusLabel: "Awaiting mentor confirmation",
    tab: "pending",
    note: "Mock behavioral interview for a fintech lead role.",
    goals: ["Mock interview"],
  },

  // PAST
  {
    id: "booking-past-1",
    title: "CV Review",
    mentorName: "AbdulLah Mumuni",
    mentorRole: "VP Product @ Kuda",
    mentorAvatar: "/sessions/mentor-abdullah.png",
    linkedinUrl: "https://linkedin.com/in/abdullah-mumuni",
    timeFormatted: "4:20 pm",
    relativeDate: "Tue, Sept 1st",
    fullDateTime: "June 8, 2026 · 3:00 pm - 3:30 pm",
    duration: "30 mins",
    durationMinutes: 30,
    price: "₦15,000",
    status: "completed",
    statusLabel: "Completed",
    tab: "past",
    rating: 4,
    hasMenteeReviewed: true,
    review:
      "You came well-prepared with specific questions, were receptive to feedback, and took detailed notes. Great session overall.",
    actionItems: [
      {
        id: "a1",
        text: "Restructure your CV to lead with impact metrics",
        completed: true,
      },
      {
        id: "a2",
        text: "Add 3 quantified achievements per role",
        completed: true,
      },
      {
        id: "a3",
        text: "Remove your outdated skills section",
        completed: false,
      },
      {
        id: "a4",
        text: "Update your LinkedIn headline to match your target role",
        completed: false,
      },
    ],
    sessionNotes:
      "You discussed CV structure and ATS optimization strategies. AbdulLah shared a CV template via session notepad. He recommends a follow-up in 2 weeks to review your revised CV.",
  },
  {
    id: "booking-past-2",
    title: "Interview Prep",
    mentorName: "Daniel Okafor",
    mentorRole: "Engineering Mentor",
    mentorAvatar: "/mentors/mentor-3.png",
    linkedinUrl: "https://linkedin.com/in/daniel-okafor",
    timeFormatted: "4:20 pm",
    relativeDate: "Tue, Sept 1st",
    fullDateTime: "Tuesday, Sept 1st, 2026 · 04:20 pm - 05:20 pm",
    duration: "60 mins",
    durationMinutes: 60,
    price: "Free",
    status: "completed",
    statusLabel: "Completed",
    tab: "past",
    hasMenteeReviewed: false,
    rating: 5,
    review:
      "Strong fundamentals on distributed systems and concurrency models. Continue practicing tree and graph algorithms.",
    actionItems: [
      {
        id: "dp1",
        text: "Solve 10 LeetCode Medium tree/graph problems",
        completed: true,
      },
      {
        id: "dp2",
        text: "Read Designing Data-Intensive Applications Chapter 5",
        completed: false,
      },
    ],
    sessionNotes:
      "Covered system design principles, distributed caching strategies, and common behavioral questions.",
  },
  {
    id: "booking-past-3",
    title: "Salary Negotiation",
    mentorName: "Adaora Nwosu",
    mentorRole: "Career Mentor",
    mentorAvatar: "/mentors/mentor-4.png",
    linkedinUrl: "https://linkedin.com/in/adaora-nwosu",
    timeFormatted: "4:20 pm",
    relativeDate: "Tue, Sept 1st",
    fullDateTime: "Tuesday, Sept 1st, 2026 · 04:20 pm - 05:05 pm",
    duration: "45 mins",
    durationMinutes: 45,
    price: "₦25,000",
    status: "completed",
    statusLabel: "Completed",
    tab: "past",
    hasMenteeReviewed: true,
    rating: 5,
    review:
      "Excellent strategic discussion on compensation packages and equity valuation. You have strong market leverage.",
    actionItems: [
      {
        id: "an1",
        text: "Benchmark compensation against Levels.fyi and local tech report",
        completed: true,
      },
    ],
    sessionNotes:
      "Discussed counter-offer frameworks and structuring non-salary benefits.",
  },

  // CANCELLED
  {
    id: "booking-cancelled-1",
    title: "Career Strategy",
    mentorName: "AbdulLah Mumuni",
    mentorRole: "VP Product @ Kuda",
    mentorAvatar: "/sessions/mentor-abdullah.png",
    linkedinUrl: "https://linkedin.com/in/abdullah-mumuni",
    timeFormatted: "4:20 pm",
    relativeDate: "Tue, Sept 1st",
    fullDateTime: "June 8, 2026 · 3:00 pm - 3:30 pm",
    duration: "30 mins",
    durationMinutes: 30,
    price: "₦25,000",
    status: "no_show",
    statusLabel: "No-show",
    tab: "cancelled",
    isNoShow: true,
    absentee: "Mentor",
    refundAmount: "₦15,000",
    note: "I've been job hunting for a while and I've not gotten positive results. I'd like to know the things I'm doing wrong.",
    goals: ["Career switch", "Fintech", "Healthtech"],
  },
  {
    id: "booking-cancelled-2",
    title: "Interview Prep",
    mentorName: "AbdulLah Mumuni",
    mentorRole: "VP Product @ Kuda",
    mentorAvatar: "/sessions/mentor-abdullah.png",
    linkedinUrl: "https://linkedin.com/in/abdullah-mumuni",
    timeFormatted: "4:20 pm",
    relativeDate: "Tue, Sept 1st",
    fullDateTime: "June 8, 2026 · 3:00 pm - 3:30 pm",
    duration: "30 mins",
    durationMinutes: 30,
    price: "₦25,000",
    status: "cancelled",
    statusLabel: "Cancelled",
    tab: "cancelled",
    cancelledBy: "You",
    cancellationNotice: "More than 24 hours before session",
    refundAmount: "₦15000",
    cancellationReason:
      "Mentee had a last-minute work conflict and requested to reschedule the CV review for a later time.",
    note: "I've been job hunting for a while and I've not gotten positive results. I'd like to know the things I'm doing wrong.",
    goals: ["Career switch", "Fintech", "Healthtech"],
  },
  {
    id: "booking-cancelled-3",
    title: "Salary Negotiation",
    mentorName: "AbdulLah Mumuni",
    mentorRole: "VP Product @ Kuda",
    mentorAvatar: "/sessions/mentor-abdullah.png",
    linkedinUrl: "https://linkedin.com/in/abdullah-mumuni",
    timeFormatted: "4:20 pm",
    relativeDate: "Tue, Sept 1st",
    fullDateTime: "June 8, 2026 · 3:00 pm - 3:30 pm",
    duration: "30 mins",
    durationMinutes: 30,
    price: "Free",
    status: "cancelled",
    statusLabel: "Cancelled",
    tab: "cancelled",
    cancelledBy: "You",
    cancellationNotice: "More than 24 hours before session",
    refundAmount: "Free",
    cancellationReason: "Resolved compensation details before scheduled call.",
    note: "I've been job hunting for a while and I've not gotten positive results. I'd like to know the things I'm doing wrong.",
    goals: ["Career switch", "Fintech", "Healthtech"],
  },
  {
    id: "booking-cancelled-4",
    title: "Product Strategy",
    mentorName: "AbdulLah Mumuni",
    mentorRole: "VP Product @ Kuda",
    mentorAvatar: "/sessions/mentor-abdullah.png",
    linkedinUrl: "https://linkedin.com/in/abdullah-mumuni",
    timeFormatted: "4:20 pm",
    relativeDate: "Tue, Sept 1st",
    fullDateTime: "June 8, 2026 · 3:00 pm - 3:30 pm",
    duration: "30 mins",
    durationMinutes: 30,
    price: "Free",
    status: "cancelled",
    statusLabel: "Cancelled",
    tab: "cancelled",
    cancelledBy: "AbdulLah Mumuni",
    cancellationNotice: "More than 24 hours before session",
    refundAmount: "Free",
    cancellationReason: "Mentor had an emergency company all-hands meeting.",
    note: "I've been job hunting for a while and I've not gotten positive results. I'd like to know the things I'm doing wrong.",
    goals: ["Career switch", "Fintech", "Healthtech"],
  },
];
